#!/bin/bash

# Run some pre commit checks on the Go source code. Prevent the commit if any errors are found
echo "Running pre-commit checks on your code..."

# Format the Go code
go fmt ./...

# Check all files for suspicious constructs
go vet ./...

golangci-lint run ./...